name: "Multi event pipeline"

on:
  push:
    branches:
      - main
      - test

  pull_request:
    branches:
      - main
    types:
      - closed

  workflow_dispatch: # manually trigger the workflow from the UI

jobs:
  on-push:
    if: github.event_name == 'push' # only run on push
    runs-on: ubuntu-latest
    steps:
      - name: "Running on main push"
        run: echo "Running on main push"

  on-pull-request-closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' # only run on pull request merged
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request closed"
        run: echo "Running on pull request closed"

  on-pull-request:
    if: github.event_name == 'pull_request' # only run on pull request
    runs-on: ubuntu-latest
    steps:
      - name: "Running on pull request"
        run: echo "Running on pull request"

  on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch' # only run on workflow dispatch
    runs-on: ubuntu-latest
    steps:
      - name: "Running on workflow dispatch"
        run: echo "Running on workflow dispatch"
